language: go
cache: vendor
go:
  - 1.8
  - 1.9
  - master


install:
  - npm install -g codeclimate-test-reporter
  - make prerequisites

script:
  - make ci
  - ./dev/coverage.sh

after_success:
  #- codeclimate-test-reporter < coverage.txt
